name = "metadata-proxy"
type = "javascript"

account_id = ""
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2022-04-03"

[vars]
CACHE_TTL = 600
RE_ORIGINS = "https*://(localhost:3000|(alpha\\.|beta\\.|)ketos\\.app)"
